#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by ChatGPT
##
##############################################################################

DIR="$( cd "$( dirname "$0" )" && pwd )"
exec "$DIR/gradlew.bat" "$@"
