#!/usr/bin/env bash
set -e

echo "===> NURTEN Hologram Showcase projesi kuruluyor..."

# Yardımcı fonksiyon
create_file() {
  local path="$1"
  shift
  mkdir -p "$(dirname "$path")"
  cat > "$path" << 'EOF'
'"$@"'
EOF
}

############################
# 1) Root Gradle dosyaları #
############################

cat > settings.gradle << 'EOF'
rootProject.name = "NurtenHologramShowcase"
include(":app")
EOF

cat > build.gradle << 'EOF'
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.7.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.0")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
EOF

mkdir -p gradle/wrapper
cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-bin.zip
EOF

cat > gradlew << 'EOF'
#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by ChatGPT
##
##############################################################################

DIR="$( cd "$( dirname "$0" )" && pwd )"
exec "$DIR/gradlew.bat" "$@"
EOF

cat > gradlew.bat << 'EOF'
@echo off
REM Dummy wrapper entry; Android Studio will regenerate proper wrapper if needed.
echo Please use Android Studio to sync Gradle wrapper.
EOF

chmod +x gradlew gradlew.bat

################################
# 2) app/build.gradle (module) #
################################

mkdir -p app
cat > app/build.gradle << 'EOF'
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.nurten.hologramshowcase"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.nurten.hologramshowcase"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")

    // ARCore
    implementation("com.google.ar:core:1.45.0")

    // Sceneform (AR 3D engine)
    implementation("com.gorisse.thomas.sceneform:sceneform:1.23.0")
}
EOF

##################################
# 3) AndroidManifest.xml         #
##################################

mkdir -p app/src/main
cat > app/src/main/AndroidManifest.xml << 'EOF'
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.nurten.hologramshowcase">

    <!-- Kamera izni (AR için) -->
    <uses-permission android:name="android.permission.CAMERA" />

    <application
        android:allowBackup="true"
        android:label="NURTEN Hologram"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.AppCompat.Light.NoActionBar">

        <activity
            android:name=".SplashActivity"
            android:exported="true"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <activity
            android:name=".MainActivity"
            android:exported="false"
            android:screenOrientation="portrait"/>

        <activity
            android:name=".HologramActivity"
            android:exported="false"
            android:screenOrientation="portrait"/>

        <activity
            android:name=".ArHologramActivity"
            android:exported="false"
            android:screenOrientation="portrait"/>
    </application>

</manifest>
EOF

##################################
# 4) RES: layout dosyaları       #
##################################

mkdir -p app/src/main/res/layout

# activity_splash.xml
cat > app/src/main/res/layout/activity_splash.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/splashRoot"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#000000">

    <View
        android:id="@+id/eclipseCircle"
        android:layout_width="220dp"
        android:layout_height="220dp"
        android:layout_gravity="center"
        android:background="@drawable/eclipse_circle" />

</FrameLayout>
EOF

# activity_main.xml
cat > app/src/main/res/layout/activity_main.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/menuRoot"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#050505"
    android:orientation="vertical"
    android:padding="28dp">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="NURTEN\nHOLOGRAM SHOWCASE"
        android:textColor="#FFFFFF"
        android:textStyle="bold"
        android:textSize="24sp"
        android:letterSpacing="0.12" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Koleksiyon seç:"
        android:textColor="#80FFFFFF"
        android:layout_marginTop="10dp" />

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="#22FFFFFF"
        android:layout_marginVertical="16dp" />

    <Button
        android:id="@+id/btnSun"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="GÜNEŞİN SICAKLIĞI"
        android:backgroundTint="#FFCFA351"
        android:textColor="#000000"
        android:layout_marginBottom="12dp" />

    <Button
        android:id="@+id/btnNature"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="DOĞAYA DÖNÜŞ"
        android:textColor="#FFFFFF"
        android:backgroundTint="#222222"
        android:layout_marginBottom="12dp"/>

    <Button
        android:id="@+id/btnLove"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="AŞK VE ŞANS"
        android:textColor="#FFFFFF"
        android:backgroundTint="#222222"
        android:layout_marginBottom="12dp"/>

    <Button
        android:id="@+id/btnTimeless"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="ZAMANSIZ AŞK"
        android:textColor="#FFFFFF"
        android:backgroundTint="#222222"
        android:layout_marginBottom="12dp"/>

    <Button
        android:id="@+id/btnWater"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="SUYUN SESİ"
        android:textColor="#FFFFFF"
        android:backgroundTint="#222222"/>

    <Button
        android:id="@+id/btnArMode"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="AR GERÇEKLİK MODU"
        android:textColor="#FFCFA351"
        android:backgroundTint="#000000"
        android:layout_marginTop="16dp" />

</LinearLayout>
EOF

# activity_hologram.xml
cat > app/src/main/res/layout/activity_hologram.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/holoRoot"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#000000">

    <VideoView
        android:id="@+id/holoVideo"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:keepScreenOn="true"/>

    <View
        android:id="@+id/flareOverlay"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#55FFC75A"/>

    <TextView
        android:id="@+id/watermark"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="NURTEN – Güneşin Sıcaklığı"
        android:textColor="#80FFFFFF"
        android:textSize="16sp"
        android:layout_gravity="bottom|center_horizontal"
        android:layout_marginBottom="22dp" />

</FrameLayout>
EOF

# activity_ar_hologram.xml
cat > app/src/main/res/layout/activity_ar_hologram.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/arRoot"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#000000">

    <fragment
        android:id="@+id/arFragment"
        android:name="com.gorisse.thomas.sceneform.ArFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <TextView
        android:id="@+id/arHint"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Yüzeyi tara, sonra ekrana dokunarak kolyeyi yerleştir"
        android:textColor="#CCFFFFFF"
        android:textSize="12sp"
        android:layout_margin="12dp"
        android:layout_gravity="top|center_horizontal" />

    <TextView
        android:id="@+id/arWatermark"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="NURTEN – Güneşin Sıcaklığı AR"
        android:textColor="#80FFFFFF"
        android:textSize="14sp"
        android:layout_marginBottom="20dp"
        android:layout_gravity="bottom|center_horizontal" />

</FrameLayout>
EOF

###############################
# 5) RES: drawable            #
###############################

mkdir -p app/src/main/res/drawable
cat > app/src/main/res/drawable/eclipse_circle.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <size android:width="220dp" android:height="220dp"/>
    <stroke android:width="3dp" android:color="#FFCFA351"/>
    <solid android:color="#000000"/>
</shape>
EOF

#######################################
# 6) Kotlin Activity dosyaları        #
#######################################

mkdir -p app/src/main/java/com/nurten/hologramshowcase

# SplashActivity.kt
cat > app/src/main/java/com/nurten/hologramshowcase/SplashActivity.kt << 'EOF'
package com.nurten.hologramshowcase

import android.content.Intent
import android.os.*
import android.view.View
import android.view.WindowManager
import android.view.animation.AlphaAnimation
import androidx.appcompat.app.AppCompatActivity

class SplashActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        window.decorView.systemUiVisibility =
            View.SYSTEM_UI_FLAG_FULLSCREEN or
            View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
            View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        setContentView(R.layout.activity_splash)

        val eclipse = findViewById<View>(R.id.eclipseCircle)
        val pulse = AlphaAnimation(0.3f, 1f).apply {
            duration = 900
            repeatMode = AlphaAnimation.REVERSE
            repeatCount = AlphaAnimation.INFINITE
        }
        eclipse.startAnimation(pulse)

        Handler(Looper.getMainLooper()).postDelayed({
            startActivity(Intent(this, MainActivity::class.java))
            finish()
        }, 1400)
    }
}
EOF

# MainActivity.kt
cat > app/src/main/java/com/nurten/hologramshowcase/MainActivity.kt << 'EOF'
package com.nurten.hologramshowcase

import android.content.Intent
import android.os.Bundle
import android.view.WindowManager
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        window.decorView.systemUiVisibility =
            android.view.View.SYSTEM_UI_FLAG_FULLSCREEN or
            android.view.View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
            android.view.View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        setContentView(R.layout.activity_main)

        fun openHolo(id: Int) {
            findViewById<Button>(id).setOnClickListener {
                startActivity(Intent(this, HologramActivity::class.java))
            }
        }

        openHolo(R.id.btnSun)
        openHolo(R.id.btnNature)
        openHolo(R.id.btnLove)
        openHolo(R.id.btnTimeless)
        openHolo(R.id.btnWater)

        findViewById<Button>(R.id.btnArMode).setOnClickListener {
            startActivity(Intent(this, ArHologramActivity::class.java))
        }
    }
}
EOF

# HologramActivity.kt
cat > app/src/main/java/com/nurten/hologramshowcase/HologramActivity.kt << 'EOF'
package com.nurten.hologramshowcase

import android.hardware.*
import android.media.MediaPlayer
import android.net.Uri
import android.os.Bundle
import android.view.View
import android.view.WindowManager
import android.widget.VideoView
import androidx.appcompat.app.AppCompatActivity

class HologramActivity : AppCompatActivity(), SensorEventListener {
    private lateinit var videoView: VideoView
    private lateinit var flareOverlay: View
    private lateinit var rootView: View
    private lateinit var sensorManager: SensorManager
    private var accel: Sensor? = null
    private var mediaPlayer: MediaPlayer? = null
    private var lastX = 0f
    private var lastY = 0f
    private val smooth = 0.15f
    private val maxOffset = 40f

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        window.decorView.systemUiVisibility =
            View.SYSTEM_UI_FLAG_FULLSCREEN or
            View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
            View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        setContentView(R.layout.activity_hologram)

        rootView = findViewById(R.id.holoRoot)
        videoView = findViewById(R.id.holoVideo)
        flareOverlay = findViewById(R.id.flareOverlay)

        setupVideo()
        setupSensors()
        flareIntro()

        rootView.setOnClickListener {
            videoView.seekTo(0)
            videoView.start()
        }
    }

    private fun setupVideo() {
        val uri = Uri.parse("android.resource://$packageName/${R.raw.sun_necklace_popout}")
        videoView.setVideoURI(uri)
        videoView.setOnPreparedListener { mp ->
            mediaPlayer = mp
            mp.isLooping = true
            mp.start()
        }
        videoView.setOnCompletionListener {
            videoView.start()
        }
    }

    private fun setupSensors() {
        sensorManager = getSystemService(SENSOR_SERVICE) as SensorManager
        accel = sensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER)
    }

    private fun flareIntro() {
        flareOverlay.alpha = 1f
        flareOverlay.animate()
            .alpha(0f)
            .setDuration(1200)
            .setStartDelay(250)
            .withEndAction {
                flareOverlay.visibility = View.GONE
            }
            .start()
    }

    override fun onSensorChanged(e: SensorEvent?) {
        if (e?.sensor?.type != Sensor.TYPE_ACCELEROMETER) return

        lastX += (e.values[0] - lastX) * smooth
        lastY += (e.values[1] - lastY) * smooth

        val tx = (-lastX / 10f) * maxOffset
        val ty = (lastY / 10f) * maxOffset

        videoView.translationX = tx
        videoView.translationY = ty
    }

    override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {}

    override fun onResume() {
        super.onResume()
        accel?.let {
            sensorManager.registerListener(this, it, SensorManager.SENSOR_DELAY_GAME)
        }
        videoView.start()
    }

    override fun onPause() {
        super.onPause()
        sensorManager.unregisterListener(this)
        videoView.pause()
    }

    override fun onDestroy() {
        super.onDestroy()
        mediaPlayer?.release()
        mediaPlayer = null
    }
}
EOF

# ArHologramActivity.kt
cat > app/src/main/java/com/nurten/hologramshowcase/ArHologramActivity.kt << 'EOF'
package com.nurten.hologramshowcase

import android.os.Bundle
import android.view.View
import android.view.WindowManager
import androidx.appcompat.app.AppCompatActivity
import com.gorisse.thomas.sceneform.ArFragment
import com.gorisse.thomas.sceneform.math.Position
import com.gorisse.thomas.sceneform.node.ModelNode
import com.gorisse.thomas.sceneform.scene.await
import com.gorisse.thomas.sceneform.scene.setOnTapArPlaneListener
import com.google.ar.core.HitResult
import kotlinx.coroutines.*

class ArHologramActivity : AppCompatActivity() {
    private lateinit var arFragment: ArFragment
    private val uiScope = CoroutineScope(Dispatchers.Main + Job())

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
        window.decorView.systemUiVisibility =
            View.SYSTEM_UI_FLAG_FULLSCREEN or
            View.SYSTEM_UI_FLAG_HIDE_NAVIGATION or
            View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
        setContentView(R.layout.activity_ar_hologram)

        arFragment = supportFragmentManager.findFragmentById(R.id.arFragment) as ArFragment

        arFragment.setOnTapArPlaneListener { hitResult: HitResult, _, _ ->
            placeNecklace(hitResult)
        }
    }

    private fun placeNecklace(hitResult: HitResult) {
        arFragment.setOnTapArPlaneListener(null)
        uiScope.launch {
            val modelInstance = arFragment.modelLoader.createModelInstance(
                assetFileLocation = "gunesin_sicakligi.glb"
            ).await()

            val node = ModelNode(
                modelInstance = modelInstance,
                anchor = hitResult.createAnchor()
            ).apply {
                position = Position(0f, 0.05f, 0f)
                scale = Position(0.2f, 0.2f, 0.2f)
                isSmoothTransformEnabled = true
                isShadowReceiver = true
                isShadowCaster = true
            }

            arFragment.addChild(node)
            node.isSelectable = true
        }
    }
}
EOF

#################################
# 7) assets + raw + placeholders#
#################################

mkdir -p app/src/main/res/raw
mkdir -p app/src/main/assets

# Placeholder for video
cat > app/src/main/res/raw/sun_necklace_popout.mp4 << 'EOF'
# Bu dosya, video içeriği için bir yer tutucudur.
# Gerçek video dosyası (sun_necklace_popout.mp4) daha sonra buraya kopyalanacaktır.
EOF

# Placeholder for 3D model
cat > app/src/main/assets/gunesin_sicakligi.glb << 'EOF'
# Bu dosya, 3D model içeriği için bir yer tutucudur.
# Gerçek 3D model dosyası (gunesin_sicakligi.glb) daha sonra buraya kopyalanacaktır.
EOF

echo "===> Kurulum tamamlandı. Video ve 3D model dosyalarını kopyalamayı unutmayın."
